version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - |
        if [ $? -eq 0 ]; then
          npm run build
        else
          echo "Tests failed. Skipping build."
          exit 1
        fi

artifacts:
  files:
    - "build/**/*"
